CREATE TABLE sequencer_projects (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  date_created TIMESTAMP DEFAULT now() NOT NULL,
  date_modified TIMESTAMP,
  project_data JSON NOT NULL,
  user_id INTEGER
    REFERENCES sequencer_users(id) ON DELETE CASCADE NOT NULL
);